In [3]:
import numpy as np
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.arange(1, 10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a + b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
r = np.argmax(a)
r

8

In [11]:
a = np.array([1, 3, 6, 9, 8, 9, 2, 5])
np.argmax(a, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1